apiVersion: v2
name: gvm
version: 1.4.0
appVersion: "22.04"
description: The Greenbone Vulnerability Management Solution (previously known as Open Vulnerability Assessment System) i.e. a remote network security auditing tool
keywords:
  - gvm
  - openvas
  - security
home: https://community.greenbone.net/
icon: https://community.greenbone.net/uploads/default/original/1X/2bd8ed1c87dd1a124f45b394039d3ec4bbf62e8e.png
sources:
  - https://github.com/admirito/gvm-containers
maintainers:
  - name: Mohammad Razavi
    twitter: "@admirito"
  - name: Olivier Rochon
    twitter: "@kshuttletech"
dependencies:
  - name: postgresql
    version: ~13.2.21
    repository: https://charts.bitnami.com/bitnami
    alias: gvmd-db

  - name: redis
    version: ~7.2.4
    repository: https://charts.bitnami.com/bitnami
    alias: openvas-redis
